/**
 * generated by Xtext 2.13.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Author</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.Author#getAuthorString <em>Author String</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getAuthor()
 * @model
 * @generated
 */
public interface Author extends EObject
{
  /**
   * Returns the value of the '<em><b>Author String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Author String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Author String</em>' attribute.
   * @see #setAuthorString(String)
   * @see cs.queensu.ca.unity.UnityPackage#getAuthor_AuthorString()
   * @model
   * @generated
   */
  String getAuthorString();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Author#getAuthorString <em>Author String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Author String</em>' attribute.
   * @see #getAuthorString()
   * @generated
   */
  void setAuthorString(String value);

} // Author
