/**
 * generated by Xtext 2.13.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Channel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.Channel#getName <em>Name</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Channel#getDirection <em>Direction</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Channel#getType <em>Type</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Channel#getPort <em>Port</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Channel#getAreaname <em>Areaname</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Channel#getQname <em>Qname</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Channel#getBoundInstances <em>Bound Instances</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getChannel()
 * @model
 * @generated
 */
public interface Channel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cs.queensu.ca.unity.UnityPackage#getChannel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Channel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direction</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see #setDirection(String)
   * @see cs.queensu.ca.unity.UnityPackage#getChannel_Direction()
   * @model
   * @generated
   */
  String getDirection();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Channel#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see #getDirection()
   * @generated
   */
  void setDirection(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(interfaceType)
   * @see cs.queensu.ca.unity.UnityPackage#getChannel_Type()
   * @model containment="true"
   * @generated
   */
  interfaceType getType();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Channel#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(interfaceType value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' containment reference.
   * @see #setPort(Port)
   * @see cs.queensu.ca.unity.UnityPackage#getChannel_Port()
   * @model containment="true"
   * @generated
   */
  Port getPort();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Channel#getPort <em>Port</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' containment reference.
   * @see #getPort()
   * @generated
   */
  void setPort(Port value);

  /**
   * Returns the value of the '<em><b>Areaname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Areaname</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Areaname</em>' containment reference.
   * @see #setAreaname(AreaName)
   * @see cs.queensu.ca.unity.UnityPackage#getChannel_Areaname()
   * @model containment="true"
   * @generated
   */
  AreaName getAreaname();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Channel#getAreaname <em>Areaname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Areaname</em>' containment reference.
   * @see #getAreaname()
   * @generated
   */
  void setAreaname(AreaName value);

  /**
   * Returns the value of the '<em><b>Qname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Qname</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qname</em>' containment reference.
   * @see #setQname(QName)
   * @see cs.queensu.ca.unity.UnityPackage#getChannel_Qname()
   * @model containment="true"
   * @generated
   */
  QName getQname();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Channel#getQname <em>Qname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qname</em>' containment reference.
   * @see #getQname()
   * @generated
   */
  void setQname(QName value);

  /**
   * Returns the value of the '<em><b>Bound Instances</b></em>' reference list.
   * The list contents are of type {@link cs.queensu.ca.unity.Instance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bound Instances</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bound Instances</em>' reference list.
   * @see cs.queensu.ca.unity.UnityPackage#getChannel_BoundInstances()
   * @model
   * @generated
   */
  EList<Instance> getBoundInstances();

} // Channel
