/**
 * generated by Xtext 2.13.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.ConfigAssignment#getConfigs <em>Configs</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getConfigAssignment()
 * @model
 * @generated
 */
public interface ConfigAssignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Configs</b></em>' containment reference list.
   * The list contents are of type {@link cs.queensu.ca.unity.Config}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Configs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configs</em>' containment reference list.
   * @see cs.queensu.ca.unity.UnityPackage#getConfigAssignment_Configs()
   * @model containment="true"
   * @generated
   */
  EList<Config> getConfigs();

} // ConfigAssignment
