/**
 * generated by Xtext 2.13.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cs.queensu.ca.unity.UnityPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
