/**
 * generated by Xtext 2.13.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Focus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.Focus#getFocusObject <em>Focus Object</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Focus#getDx <em>Dx</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Focus#getDy <em>Dy</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Focus#getDz <em>Dz</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getFocus()
 * @model
 * @generated
 */
public interface Focus extends EObject
{
  /**
   * Returns the value of the '<em><b>Focus Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Focus Object</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Focus Object</em>' reference.
   * @see #setFocusObject(Instance)
   * @see cs.queensu.ca.unity.UnityPackage#getFocus_FocusObject()
   * @model
   * @generated
   */
  Instance getFocusObject();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Focus#getFocusObject <em>Focus Object</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Focus Object</em>' reference.
   * @see #getFocusObject()
   * @generated
   */
  void setFocusObject(Instance value);

  /**
   * Returns the value of the '<em><b>Dx</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dx</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dx</em>' attribute.
   * @see #setDx(double)
   * @see cs.queensu.ca.unity.UnityPackage#getFocus_Dx()
   * @model
   * @generated
   */
  double getDx();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Focus#getDx <em>Dx</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dx</em>' attribute.
   * @see #getDx()
   * @generated
   */
  void setDx(double value);

  /**
   * Returns the value of the '<em><b>Dy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dy</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dy</em>' attribute.
   * @see #setDy(double)
   * @see cs.queensu.ca.unity.UnityPackage#getFocus_Dy()
   * @model
   * @generated
   */
  double getDy();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Focus#getDy <em>Dy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dy</em>' attribute.
   * @see #getDy()
   * @generated
   */
  void setDy(double value);

  /**
   * Returns the value of the '<em><b>Dz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dz</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dz</em>' attribute.
   * @see #setDz(double)
   * @see cs.queensu.ca.unity.UnityPackage#getFocus_Dz()
   * @model
   * @generated
   */
  double getDz();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Focus#getDz <em>Dz</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dz</em>' attribute.
   * @see #getDz()
   * @generated
   */
  void setDz(double value);

} // Focus
