/**
 * generated by Xtext 2.13.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cs.queensu.ca.unity.UnityPackage#getRef()
 * @model
 * @generated
 */
public interface Ref extends EObject
{
} // Ref
