/*
 * generated by Xtext 2.13.0
 */
package cs.queensu.ca.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractUnityValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(cs.queensu.ca.unity.UnityPackage.eINSTANCE);
		return result;
	}
	
}
