/*
 * generated by Xtext 2.13.0
 */
package cs.queensu.ca.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUnityScopeProvider extends DelegatingScopeProvider {
}
