/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.ide;

import cs.queensu.ca.ide.AbstractUnityIdeModule;

/**
 * lll
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class UnityIdeModule extends AbstractUnityIdeModule {
}
