##################################################
# Default makefile
# Redirect make to target makefile
##################################################

all:
	make -f MakefileTOP.mk all
clean:
	make -f MakefileTOP.mk clean
.PHONY: 
	make -f MakefileTOP.mk all clean
