/*
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.parser.antlr;

import com.google.inject.Inject;
import cs.queensu.ca.parser.antlr.internal.InternalUnityParser;
import cs.queensu.ca.services.UnityGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class UnityParser extends AbstractAntlrParser {

	@Inject
	private UnityGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUnityParser createParser(XtextTokenStream stream) {
		return new InternalUnityParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Specification";
	}

	public UnityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UnityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
