/*
 * generated by Xtext 2.12.0
 */
package cs.queensu.ca.ui.tests;

import com.google.inject.Injector;
import cs.queensu.ca.Unity.ui.internal.UnityActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class UnityUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UnityActivator.getInstance().getInjector("cs.queensu.ca.Unity");
	}

}
