/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cs.queensu.ca.unity.UnityPackage#getCompositeRef()
 * @model
 * @generated
 */
public interface CompositeRef extends EObject
{
} // CompositeRef
