/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.unity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dot Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.DotExpression#getHead <em>Head</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.DotExpression#getTail <em>Tail</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getDotExpression()
 * @model
 * @generated
 */
public interface DotExpression extends CompositeRef
{
  /**
   * Returns the value of the '<em><b>Head</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Head</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Head</em>' containment reference.
   * @see #setHead(CompositeRef)
   * @see cs.queensu.ca.unity.UnityPackage#getDotExpression_Head()
   * @model containment="true"
   * @generated
   */
  CompositeRef getHead();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.DotExpression#getHead <em>Head</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Head</em>' containment reference.
   * @see #getHead()
   * @generated
   */
  void setHead(CompositeRef value);

  /**
   * Returns the value of the '<em><b>Tail</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tail</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tail</em>' reference.
   * @see #setTail(Property)
   * @see cs.queensu.ca.unity.UnityPackage#getDotExpression_Tail()
   * @model
   * @generated
   */
  Property getTail();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.DotExpression#getTail <em>Tail</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tail</em>' reference.
   * @see #getTail()
   * @generated
   */
  void setTail(Property value);

} // DotExpression
