/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.unity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Identifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.Identifier#getRefrence <em>Refrence</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getIdentifier()
 * @model
 * @generated
 */
public interface Identifier extends Expression
{
  /**
   * Returns the value of the '<em><b>Refrence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refrence</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refrence</em>' containment reference.
   * @see #setRefrence(Ref)
   * @see cs.queensu.ca.unity.UnityPackage#getIdentifier_Refrence()
   * @model containment="true"
   * @generated
   */
  Ref getRefrence();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Identifier#getRefrence <em>Refrence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refrence</em>' containment reference.
   * @see #getRefrence()
   * @generated
   */
  void setRefrence(Ref value);

} // Identifier
