/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.unity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.IntLiteral#getInt <em>Int</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getIntLiteral()
 * @model
 * @generated
 */
public interface IntLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see cs.queensu.ca.unity.UnityPackage#getIntLiteral_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.IntLiteral#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

} // IntLiteral
