/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.unity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cs.queensu.ca.unity.UnityPackage#getLiteral()
 * @model
 * @generated
 */
public interface Literal extends Expression
{
} // Literal
