/**
 * generated by Xtext 2.12.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.Map#getMapName <em>Map Name</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Map#getPathName <em>Path Name</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getMap()
 * @model
 * @generated
 */
public interface Map extends EObject
{
  /**
   * Returns the value of the '<em><b>Map Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Map Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map Name</em>' attribute.
   * @see #setMapName(String)
   * @see cs.queensu.ca.unity.UnityPackage#getMap_MapName()
   * @model
   * @generated
   */
  String getMapName();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Map#getMapName <em>Map Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map Name</em>' attribute.
   * @see #getMapName()
   * @generated
   */
  void setMapName(String value);

  /**
   * Returns the value of the '<em><b>Path Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Path Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path Name</em>' containment reference.
   * @see #setPathName(StLiteral)
   * @see cs.queensu.ca.unity.UnityPackage#getMap_PathName()
   * @model containment="true"
   * @generated
   */
  StLiteral getPathName();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Map#getPathName <em>Path Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path Name</em>' containment reference.
   * @see #getPathName()
   * @generated
   */
  void setPathName(StLiteral value);

} // Map
