/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cs.queensu.ca.unity.UnityPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
} // Property
