/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.unity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.RealLiteral#getIntPart <em>Int Part</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.RealLiteral#getDecimalPart <em>Decimal Part</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getRealLiteral()
 * @model
 * @generated
 */
public interface RealLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Int Part</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int Part</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Part</em>' attribute.
   * @see #setIntPart(int)
   * @see cs.queensu.ca.unity.UnityPackage#getRealLiteral_IntPart()
   * @model
   * @generated
   */
  int getIntPart();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.RealLiteral#getIntPart <em>Int Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Part</em>' attribute.
   * @see #getIntPart()
   * @generated
   */
  void setIntPart(int value);

  /**
   * Returns the value of the '<em><b>Decimal Part</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decimal Part</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decimal Part</em>' attribute.
   * @see #setDecimalPart(int)
   * @see cs.queensu.ca.unity.UnityPackage#getRealLiteral_DecimalPart()
   * @model
   * @generated
   */
  int getDecimalPart();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.RealLiteral#getDecimalPart <em>Decimal Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decimal Part</em>' attribute.
   * @see #getDecimalPart()
   * @generated
   */
  void setDecimalPart(int value);

} // RealLiteral
