/**
 * generated by Xtext 2.12.0
 */
package cs.queensu.ca.unity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.SingleRef#getSingleRef <em>Single Ref</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getSingleRef()
 * @model
 * @generated
 */
public interface SingleRef extends Ref
{
  /**
   * Returns the value of the '<em><b>Single Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Single Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Single Ref</em>' reference.
   * @see #setSingleRef(Property)
   * @see cs.queensu.ca.unity.UnityPackage#getSingleRef_SingleRef()
   * @model
   * @generated
   */
  Property getSingleRef();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.SingleRef#getSingleRef <em>Single Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Single Ref</em>' reference.
   * @see #getSingleRef()
   * @generated
   */
  void setSingleRef(Property value);

} // SingleRef
