/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca;

import cs.queensu.ca.UnityStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UnityStandaloneSetup extends UnityStandaloneSetupGenerated {
  public static void doSetup() {
    new UnityStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
