/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca;

import cs.queensu.ca.AbstractUnityRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UnityRuntimeModule extends AbstractUnityRuntimeModule {
}
