/**
 * generated by Xtext 2.11.0
 */
package cs.queensu.ca.validation;

import cs.queensu.ca.validation.AbstractUnityValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class UnityValidator extends AbstractUnityValidator {
}
